# This is a configuration file for gpm with toml format.

title = "gpm(Go Package Manager)"
version = "v0.2.0 Build 0524"
user_language = "en-US"
#user_language = "zh-CN"
auto_backup = true

[account]
username = ""
password = ""
github_access_token = ""

[auto_enable]
build = []
install = []