# This is a configuration file for gpm with toml format.

title = "gpm(Go Package Manager)"
version = "v0.1.5 Build 0523"
user_language = "en-US"
#user_language = "zh-CN"

[account]
username = ""
password = ""
github_access_token = ""
